# Generated by Django 4.0.2 on 2022-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestas',
            name='amabilidadCC',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Trasferencia...)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='amabilidadFT',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Tesorería: Pago de cajas menores y...)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='amabilidadSSCE',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Entrega de insumos por parte de proveedores ...)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='efectividadFT',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Tesorería: Pago de cajas menores y...)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='efectividadSSCE',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Entrega de insumos ...)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteAUD',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Mesa de ayuda)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteCC',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Trasferencia de ordenes y servicio al usuario final)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteFC',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Cuentas por pagar)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteFT',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Tesorería: Pago de cajas menores y recolección de dinero PROSEGUR)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteFV',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Ventas POS y Cuentas por cobrar)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteGA',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Arriendos y vigilancia)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteMC',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Comunicación de campañas...)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteRHC',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Contratación)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteRHN',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Nomina)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteSSCA',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(AXIONLOG)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteSSCC',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Compras)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteSSCE',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Entrega de insumos por parte de proveedores; NO AXIONLOG)', max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='soporteTEC',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Sistema de venta POS...', max_length=1),
        ),
    ]
