# Generated by Django 4.0.2 on 2022-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_alter_encuestas_amabilidadcc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestas',
            name='soporteRHC',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='(Contratación)'),
        ),
    ]
