# Generated by Django 4.0.2 on 2022-04-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0006_alter_encuestas_amabilidadaud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
