# Generated by Django 4.0.2 on 2022-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0007_alter_encuestas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestas',
            name='amabilidadFC',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Cuentas por pagar)'),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='amabilidadFV',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Ventas POS ...)'),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='amabilidadRHC',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Contratación)'),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='amabilidadRHN',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Nomina)'),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='efectividadFC',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Cuentas por pagar)'),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='efectividadFV',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Ventas POS ...)'),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='efectividadRHC',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Contratación)'),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='efectividadRHN',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='(Nomina)'),
        ),
    ]
