# Generated by Django 4.0.2 on 2022-04-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0008_alter_encuestas_amabilidadfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestas',
            name='fecha',
            field=models.DateField(),
        ),
    ]
