# Generated by Django 4.0.2 on 2022-04-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0011_encuestas_area_alter_encuestas_amabilidadaud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='encuestas',
            name='area',
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=45)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.areas')),
            ],
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.cargos'),
        ),
    ]
