# Generated by Django 4.0.2 on 2022-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0012_areas_remove_encuestas_area_cargos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area',
            field=models.CharField(choices=[('2', 'Customer Service'), ('1', 'Tienda')], max_length=45),
        ),
        migrations.AlterField(
            model_name='encuestas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
