# Generated by Django 4.0.2 on 2022-04-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0013_alter_areas_area_alter_encuestas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area',
            field=models.CharField(choices=[('2', 'Customer Service'), ('1', 'Centro de soporte')], max_length=45),
        ),
    ]
