# Generated by Django 4.0.2 on 2022-03-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='doc_file',
            field=models.FileField(default='', upload_to='static/file/%Y/%m/%d/'),
        ),
    ]
