# Generated by Django 4.0.2 on 2022-03-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_solicitudes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='doc_file',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
