# Generated by Django 4.0.2 on 2022-04-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_alter_documentos_doc_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
