# Generated by Django 4.0.2 on 2022-04-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='autor',
            new_name='user',
        ),
    ]
