# Generated by Django 4.0.2 on 2022-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_rename_autor_reporte_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='imagen',
        ),
        migrations.AddField(
            model_name='reporte',
            name='documento',
            field=models.FileField(default='', upload_to='reports'),
        ),
    ]
